name: Deploy

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: [Build]
  #   types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo 'The triggering workflow failed'
          exit 1
  on-success:
    runs-on: macos-13
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Commit SHA
      run: echo $GITHUB_SHA
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Import provisioning
      run: provisioning/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.PROVISIONING_PASSWORD }}
    - name: Set build number
      run: provisioning/set_build_number.sh
    - name: Build archive and export
      run: ./build_archive.sh
    - name: Deploy App to Apple
      run: xcrun altool --upload-app --verbose --type ios --file DerivedData/ipa/GitInbox.ipa --username "${{ secrets.APPSTORE_CONNECT_USERNAME }}" --password "${{ secrets.APPSTORE_CONNECT_PASSWORD }}"
