name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  Deploy:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Commit SHA
      run: echo $GITHUB_SHA
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Dump file hierarchy
      run: ls -R
    - name: Import provisioning
      run: provisioning/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.PROVISIONING_PASSWORD }}
    - name: Set build number
      run: provisioning/set_build_number.sh
    - name: Build archive and export
      run: ./build_archive.sh
    - name: Deploy App to Apple
      run: |
        xcrun altool --upload-app --type ios \
          --file DerivedData/ipa/GitInbox.ipa \
          --username "${{ secrets.APPSTORE_CONNECT_USERNAME }}" \
          --password "${{ secrets.APPSTORE_CONNECT_PASSWORD }}" --verbose
