name: Deploy

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Dump file hierarchy
      run: ls -R
